server:
  port: 9005

spring:
  application:
    name: registration-service

  datasource:
    url: jdbc:mysql://localhost:3307/EventZen_db
    username: EventZen_user
    password: EventZen_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # IMPORTANT (same as other services)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
