server:
  port: 9007

spring:
  application:
    name: notification-service

brevo:
  api-key: ${BREVO_API_KEY}
  sender-email: ${BREVO_SENDER_EMAIL}
  sender-name: ${BREVO_SENDER_NAME}

logging:
  level:
    org.springframework.web: INFO