server:
  port: 9008

spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:mysql://localhost:3307/EventZen_db
    username: EventZen_user
    password: EventZen_pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
